### ISSUE TITLE
Some minor issues with the antenna switch extension

### ISSUE THREAD

**Issue by SM2BYC** [OH1KK/KiwiSDR-antenna-switch-extension#29]
I have noticed some minor issues with the antenna switch extension:

1. With 8 antennas defined, the description for the 8th antenna is located partly outside the extension area. Perhaps the layout could be changed slightly to accommodate also antenna 8 within the extension area.
2. When all four Rx are in use and the last user activates the antenna switch extension, the extension shows selected antenna: unknown and permissions: unknown. Also the current antenna is not shown. I think it is still possible to select antennas but no feedback is given.

![screenshot_2019-02-07 kiwisdr](https://user-images.githubusercontent.com/47424607/52422308-19855280-2af6-11e9-8652-d3628a8295aa.png)

3. As the antenna switch extension is very popular, the log is often filled with "GET Antenna" entries. Would it be possible to suppress these messages from the log? The "SET Antenna" entries are however of interest as they show which antennas are most popular.

![screenshot_2019-02-06 admin kiwisdr](https://user-images.githubusercontent.com/47424607/52422407-4b96b480-2af6-11e9-9005-7c08d8c86a1d.png)

Regards

Mauritz / SM2BYC

**Comment by jks-prv** [comment]
Hi Mauritz. What browser are you using? I was the last one to fiddle with the button layout and I tuned the enclosing box height to fit (see below from Firefox). Does your extension box not have the margin and rounded corners? I notice there is no margin at the top for the close (X) and help buttons.

I can fix the stray messages in the log. The other problem I'm not sure about.

![image](https://user-images.githubusercontent.com/5783323/52432713-0d3ddb80-2b70-11e9-8772-813e9d2ee9ba.png)

**Comment by SM2BYC** [comment]
Hi John,

Using latest Firefox on a Windows 7 machine. Yes it has rounded corners but Antenna 8 description is partially outside the box. Good to hear that you can fix the log issue.

/ Mauritz

![screenshot_2019-02-07 kiwisdr 1](https://user-images.githubusercontent.com/47424607/52433782-1e560080-2b0e-11e9-8d37-4d1ab4eb63ca.png)

**Comment by jks-prv** [comment]
Okay. I'm looking at the code now and I see that I actually compute the "optimal" height with a formula to enclose the configured number of buttons. So it's obviously not doing the right thing on Windows. I have a W10 machine here so I can check it on that.

**Comment by SM2BYC** [comment]
Checked on of my Win10 machines and it has the same issue with Antenna 8.

**Comment by jks-prv** [comment]
My W10 machine was fine, but this might due to differences with browser fonts.

Anyway, all these problems have been fixed in my fork and a pull request has been submitted to Kari.

**Comment by SM2BYC** [comment]
OK, Thanks John.
