### ISSUE TITLE
Syntax error in reset-to-default-antennas-when-no-users-online

### ISSUE THREAD

**Issue by RipperFox** [OH1KK/KiwiSDR-antenna-switch-extension#35]
Line 67 fails if the variable never has been set (empty string ""):

`if [ $FORBIDSWITCH -eq 1 ]; then`

fix could be comparing strings:

`if  [ "$FORBIDSWITCH" =  "1" ]; then`

**Comment by OH1KK** [comment]
Thank you. Script updated.
